# Generated by Django 2.2.7 on 2019-11-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('Smartphone', 'Смартфон'), ('Car', 'Автомобиль'), ('Furniture', 'Мебель'), ('Bike', 'Велосипед'), ('NoCat', 'Без категории')], default='NoCat', max_length=15)),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
                ('email', models.EmailField(default='sanek@gmail.com', max_length=254)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
