# Generated by Django 2.2.5 on 2019-09-05 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('Smartphone', 'Смартфон'), ('Car', 'Автомобиль'), ('Furniture', 'Мебель'), ('Bike', 'Велосипед'), ('NoCat', 'Без категории')], default='NoCat', max_length=15)),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
