# Generated by Django 2.2.5 on 2019-09-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
