# Generated by Django 2.2.5 on 2019-09-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20190905_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='sanek@gmail.com', max_length=254),
        ),
    ]
