# Generated by Django 2.2.5 on 2019-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190909_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.CharField(choices=[('Смартфон', 'Смартфон'), ('Автомобиль', 'Автомобиль'), ('Мебель', 'Мебель'), ('Велосипед', 'Велосипед'), ('Без категории', 'Без категории')], default='Без категории', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
