# Generated by Django 2.2.5 on 2019-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190909_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=40, verbose_name='Наименование'),
        ),
    ]
