# Generated by Django 2.2.5 on 2019-09-09 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20190909_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.CharField(choices=[('Смартфон', 'Смартфон'), ('Автомобиль', 'Автомобиль'), ('Мебель', 'Мебель'), ('Велосипед', 'Велосипед'), ('Без категории', 'Без категории')], default='Без категории', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
